In [1]:
import numpy as np

# Given matrix
A = np.array([[1, 0.2, 0.5],
              [0.2, 1, 0.8],
              [0.5, 0.8, 1]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Original Matrix A:")
print(A)
print("\nInverse of Matrix A:")
print(A_inv)


Original Matrix A:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Inverse of Matrix A:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
